#!/bin/sh

IPT="/sbin/iptables"
INET_IFACE=eth0
LXC_IFACE=lxcbr0
VPN_IFACE=tap0

# Required to enable IPv4 forwarding.
# Redhat users can try setting FORWARD_IPV4 in /etc/sysconfig/network to true
# Alternatively, it can be set in /etc/sysctl.conf
if [ "$SYSCTL" = "" ]
then
    echo "1" > /proc/sys/net/ipv4/ip_forward
else
    $SYSCTL net.ipv4.ip_forward="1"
fi

# This enables dynamic address hacking.
# This may help if you have a dynamic IP address \(e.g. slip, ppp, dhcp\).
if [ "$SYSCTL" = "" ]
then
    echo "1" > /proc/sys/net/ipv4/ip_dynaddr
else
    $SYSCTL net.ipv4.ip_dynaddr="1"
fi

# Flush old rules, old custom tables
$IPT --flush
$IPT --delete-chain

# Flush all rules
$IPT -F
$IPT -t nat -F
$IPT -t mangle -F

# Erase all non-default chains
$IPT -X
$IPT -t nat -X
$IPT -t mangle -X

# Set default policies for all three default chains
$IPT -P INPUT DROP
$IPT -P FORWARD DROP
$IPT -P OUTPUT ACCEPT

# Enable free use of loopback interfaces
$IPT -A INPUT -i lo -j ACCEPT
$IPT -A OUTPUT -o lo -j ACCEPT

# All TCP sessions should begin with SYN
$IPT -A INPUT -p tcp ! --syn -m state --state NEW -s 0.0.0.0/0 -j DROP

# Accept inbound ICMP messages
$IPT -A INPUT -p ICMP --icmp-type 8 -s 0.0.0.0/0 -j ACCEPT
$IPT -A INPUT -p ICMP --icmp-type 11 -s 0.0.0.0/0 -j ACCEPT

#Accept related/established sessions
$IPT -A INPUT -p ALL -m state --state ESTABLISHED,RELATED -j ACCEPT

#Enable NAT (lxc->inet)
$IPT -A FORWARD -i $LXC_IFACE -o $INET_IFACE -d 0.0.0.0/0 -j ACCEPT
$IPT -A FORWARD -o $LXC_IFACE -i $INET_IFACE -s 0.0.0.0/0 -j ACCEPT
$IPT -t nat -A POSTROUTING -o $INET_IFACE -j MASQUERADE

#Enable DHCP requests from container
$IPT -A INPUT -i $LXC_IFACE -p UDP --destination-port 67 -j ACCEPT

#Redirect connections on port 22 from VPN interface to container's port 22
$IPT -t nat -A PREROUTING -i $VPN_IFACE -p tcp --dport 22 -j DNAT --to-destination 10.0.3.2:22
$IPT -A FORWARD -i $LXC_IFACE -o $VPN_IFACE -s 10.0.3.2 -j ACCEPT
$IPT -A FORWARD -o $LXC_IFACE -i $VPN_IFACE -d 10.0.3.2  -j ACCEPT


