#!/bin/sh

# Mark a specified block device as read-write
[ $# -eq 1 ] || exit
[ ! -z "$1" ] || exit
bdev="$1"
[ -b "/dev/$bdev" ] || exit
[ ! -z ${bdev##loop*} ] || exit
blockdev --setrw "/dev/$bdev" || logger "wrtblk: blockdev --setrw /dev/$bdev failed!"

# Mark a parent block device as read-write
bdev=$(echo "$bdev" | sed 's/\//!/g')
syspath=$(echo /sys/block/*/"$bdev")
[ "$syspath" = "/sys/block/*/$bdev" ] && exit
dir=${syspath%/*}
parent=${dir##*/}
parent=$(echo "$parent" | sed 's/!/\//g')
[ -b "/dev/$parent" ] || exit
blockdev --setrw "/dev/$parent" || logger "wrtblk: blockdev --setrw /dev/$parent failed!"
