#!/bin/sh

# Mark a specified block device as read-only
[ $# -eq 1 ] || exit
[ ! -z "$1" ] || exit
bdev="$1"
[ -b "/dev/$bdev" ] || exit
[ ! -z ${bdev##loop*} ] || exit
blockdev --setro "/dev/$bdev" || logger "wrtblk: blockdev --setro /dev/$bdev failed!"

# Mark all child block devices as read-only
bdev=$(echo "$bdev" | sed 's/\//!/g')
for child in /sys/block/"$bdev"/*/dev; do
	dir=${child%/*}
	partition=${dir##*/}
	[ "$partition" = '*' ] && break
	partition=$(echo "$partition" | sed 's/!/\//g')
	[ -b "/dev/$partition" ] || continue
	blockdev --setro "/dev/$partition" || logger "wrtblk: blockdev --setro /dev/$partition failed!"
done
